#!/bin/bash
python devices.py -p ARGO_MERCHANT --folder ./cf -o ./devices
python devices.py -p BARNEGAT --folder ./cf -o ./devices
python devices.py -p BARNEGAT_2014 --folder ./cf -o ./devices
python devices.py -p BUZZ_BAY --folder ./cf -o ./devices
python devices.py -p BW2011 --folder ./cf -o ./devices
python devices.py -p CALCSTWET --folder ./cf -o ./devices
python devices.py -p CAMP --folder ./cf -o ./devices
python devices.py -p CAPE_COD_BAY --folder ./cf -o ./devices
python devices.py -p CC_MISC --folder ./cf -o ./devices
python devices.py -p CHANDELEUR_13 --folder ./cf -o ./devices
python devices.py -p CHINCOTEAGUE --folder ./cf -o ./devices
python devices.py -p DAUPHIN --folder ./cf -o ./devices
python devices.py -p DEEP_REEF --folder ./cf -o ./devices
python devices.py -p DIAMONDSHOALS --folder ./cf -o ./devices
python devices.py -p DWDS_106 --folder ./cf -o ./devices
python devices.py -p ECOHAB_I --folder ./cf -o ./devices
python devices.py -p ECOHAB_II --folder ./cf -o ./devices
python devices.py -p EUROSTRATAFORM --folder ./cf -o ./devices
python devices.py -p FARALLONES --folder ./cf -o ./devices
python devices.py -p FI12 --folder ./cf -o ./devices
python devices.py -p FI14 --folder ./cf -o ./devices
python devices.py -p GB_SED --folder ./cf -o ./devices
python devices.py -p GLOBEC_GB --folder ./cf -o ./devices
python devices.py -p GLOBEC_GSC --folder ./cf -o ./devices
python devices.py -p GOMEX_CI --folder ./cf -o ./devices
python devices.py -p GULF_MAINE --folder ./cf -o ./devices
python devices.py -p HUDSON_SVALLEY --folder ./cf -o ./devices
python devices.py -p HURRIRENE_bb --folder ./cf -o ./devices
python devices.py -p KARIN_RIDGE --folder ./cf -o ./devices
python devices.py -p LYDONIA_C --folder ./cf -o ./devices
python devices.py -p MAB_SED --folder ./cf -o ./devices
python devices.py -p MAMALA_BAY --folder ./cf -o ./devices
python devices.py -p MBAY_CIRC --folder ./cf -o ./devices
python devices.py -p MBAY_IWAVE --folder ./cf -o ./devices
python devices.py -p MBAY_LT --folder ./cf -o ./devices
python devices.py -p MBAY_LTB --folder ./cf -o ./devices
python devices.py -p MBAY_STELL --folder ./cf -o ./devices
python devices.py -p MBAY_WEST --folder ./cf -o ./devices
python devices.py -p MOBILE_BAY --folder ./cf -o ./devices
python devices.py -p MONTEREY_BAY --folder ./cf -o ./devices
python devices.py -p MONTEREY_CAN --folder ./cf -o ./devices
python devices.py -p MVCO_11 --folder ./cf -o ./devices
python devices.py -p MVCO_14 --folder ./cf -o ./devices
python devices.py -p MYRTLEBEACH --folder ./cf -o ./devices
python devices.py -p NE_SLOPE --folder ./cf -o ./devices
python devices.py -p NEARSHORE --folder ./cf -o ./devices
python devices.py -p OCEANOG_C --folder ./cf -o ./devices
python devices.py -p ORANGE_COUNTY --folder ./cf -o ./devices
python devices.py -p PONCHARTRAIN --folder ./cf -o ./devices
python devices.py -p PV_SHELF --folder ./cf -o ./devices
python devices.py -p PV_SHELF04 --folder ./cf -o ./devices
python devices.py -p PV_SHELF07 --folder ./cf -o ./devices
python devices.py -p RCNWR --folder ./cf -o ./devices
python devices.py -p SAB_SED --folder ./cf -o ./devices
python devices.py -p SANDWICH2016 --folder ./cf -o ./devices
python devices.py -p SOUTHERN_CAL --folder ./cf -o ./devices
python devices.py -p STRESS --folder ./cf -o ./devices
python devices.py -p WFAL --folder ./cf -o ./devices
python devices.py -p WRIGHTSVILLE --folder ./cf -o ./devices
